# Generated by Django 3.2 on 2021-04-25 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('choice_1', models.CharField(max_length=50)),
                ('choice_2', models.CharField(max_length=50)),
                ('choice_3', models.CharField(max_length=50)),
                ('right_answer', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('for_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_questions.quiz')),
            ],
            options={
                'verbose_name': 'Question_Answer',
                'verbose_name_plural': 'Questions_Answers',
            },
        ),
    ]
