# Generated by Django 3.2 on 2021-04-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswers',
            name='right_answer',
            field=models.CharField(max_length=50),
        ),
    ]
