# Generated by Django 3.2 on 2021-04-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
